### ISSUE TITLE
max limit google api is 5000 chars per request - you should prepare module for that

### ISSUE THREAD

**Issue by sebadiginet** [fballiano/magento-full-catalog-translate#14]
One request has 5000 limit characters. When module is translating descripion of products its really small. Your module should make few request instead one. Result is without error for some products we dont have translations of longer descriptions. Please give me info if you will make solution.

**Comment by fballiano** [comment]
I didn't know that, it would be pretty tricky to split the text (if you break the sentence it will make no sense) do you have ideas about that?

At the moment I'm really short on time so I don't know when I'll be able to look into that.

**Comment by sebadiginet** [comment]
Dear Fabrizio

Thanks for you answer.
Yes i have idea that text are mostly html (specially if its longer text) so its easy to use html tags to split it.


Best Regards
Sebastian Bojczuk

**Comment by fballiano** [comment]
Also if I traslate every "<p>" separately we will never be sure they'll be less than 5000chars. And it would not be easy to manage the split/join of the sentences cause it's gonna be very easy to break everything due to the enormous amount of things people can write/import in product descriptions.

At the moment I'll write a note in the README and leave the issue open until we find the right way to do it.

Thanks anyway for reporting it.

**Comment by fballiano** [comment]
would it be useful to add a check:
if text>5000 chars alert on command line and record skipped for safety (better than a broken html description)

**Comment by fballiano** [comment]
I committed this check, as in the comment above, for 0.7.2, can't do much more.

I suggest you to create more description attributes, translate them and then join them in the real "description" attribute, but that has to be a custom development for every project I think, it's too "deep" to standardize it.
